// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package db

import (
	"database/sql"
)

type Post struct {
	ID        int32
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
	Url       string
	Caption   sql.NullString
	Lat       sql.NullFloat64
	Lng       sql.NullFloat64
	UserID    int32
}

type User struct {
	ID        int32
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
	Username  string
	Bio       sql.NullString
	Avatar    sql.NullString
	Phone     sql.NullString
	Email     sql.NullString
	Password  sql.NullString
	Status    sql.NullString
}
