// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0
// source: query.sql

package db

import (
	"context"
	"database/sql"
	"encoding/json"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
  username, bio, avatar,phone,email,password,status
) 
SELECT 
	username,
	bio,
	avatar,
	phone,
	email,
	password,
	status
FROM jsonb_populate_record(null::users, $1) RETURNING id
`

func (q *Queries) CreateUser(ctx context.Context, payload json.RawMessage) (int32, error) {
	row := q.db.QueryRowContext(ctx, createUser, payload)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users
WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteUser, id)
	return err
}

const getUser = `-- name: GetUser :one
select jsonb_build_object(
	'id',id, 
	'username',username, 
	'avatar',avatar,
	'phone',phone,
	'email',email,
	'password',password,
	'status',status)
from (
	SELECT id, created_at, updated_at, username, bio, avatar, phone, email, password, status FROM USERS WHERE ID=$1
)AS selectedUser
`

func (q *Queries) GetUser(ctx context.Context, id int32) (json.RawMessage, error) {
	row := q.db.QueryRowContext(ctx, getUser, id)
	var jsonb_build_object json.RawMessage
	err := row.Scan(&jsonb_build_object)
	return jsonb_build_object, err
}

const listUsers = `-- name: ListUsers :one
select jsonb_agg(jsonb_build_object(
	'id',id, 
	'username',username, 
	'avatar',avatar,
	'phone',phone,
	'email',email,
	'password',password,
	'status',status))
from (
	SELECT id, created_at, updated_at, username, bio, avatar, phone, email, password, status FROM USERS ORDER BY id ASC
)AS sortedUser
`

func (q *Queries) ListUsers(ctx context.Context) (json.RawMessage, error) {
	row := q.db.QueryRowContext(ctx, listUsers)
	var jsonb_agg json.RawMessage
	err := row.Scan(&jsonb_agg)
	return jsonb_agg, err
}

const updateUser = `-- name: UpdateUser :exec
UPDATE USERS
SET 
	username = $2,
	bio=$3,
	avatar=$4,
	phone=$5,
	email=$6,
	password=$7,
	status=$8
WHERE ID=$1
`

type UpdateUserParams struct {
	ID       int32
	Username string
	Bio      sql.NullString
	Avatar   sql.NullString
	Phone    sql.NullString
	Email    sql.NullString
	Password sql.NullString
	Status   sql.NullString
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) error {
	_, err := q.db.ExecContext(ctx, updateUser,
		arg.ID,
		arg.Username,
		arg.Bio,
		arg.Avatar,
		arg.Phone,
		arg.Email,
		arg.Password,
		arg.Status,
	)
	return err
}
